### ISSUE TITLE
[Bug] HarmonyPatch fails to apply(?) to the menu component

### ISSUE THREAD

**Issue by raineaeternal** [Exomanz/MenuSaberColors#1] opened 2022-03-24 20:27 UTC
https://pastebin.com/P27iMrPf <----- The whole thing is here (with multiple attempts

Only way to fix this is to go out and back into solo.

**Comment by Exomanz** [comment] 2022-03-24 21:59
After some testing I was unable to reproduce the issue myself. 

I've seen `FieldAccessor`'s fail before, so I wrapped the statement in a `try` block, falling back on reflection if it ever ~fails~ catches.
Pushing commits and closing.

**Closed as completed** 2022-03-24 22:10 UTC
Labels: bug
